# Generated by Django 5.0.6 on 2024-05-28 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Website',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(unique=True)),
                ('country', models.CharField(max_length=100)),
                ('palette', models.JSONField(blank=True, null=True)),
            ],
        ),
    ]
