# Generated by Django 5.0.6 on 2024-05-29 11:54

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('palette_analyzer', '0002_alter_website_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='website',
            name='palette',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), size=3), blank=True, null=True, size=10),
        ),
    ]
