# Generated by Django 5.0.6 on 2024-05-27 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('font_extractor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArrayModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='fontsize',
            name='font_size',
            field=models.CharField(max_length=500),
        ),
    ]
